import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import NextAuthSessionProvider from "@/app/utils/sessionProvider";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full h-full bg-[#2F322F]">
        <main className="w-[100%] bg-[#2F322F] h-[100svh] relative max-w-[1600px] flex m-auto">
          <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
          <Toaster />
        </main>
      </body>
    </html>
  );
}
